# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sequence_generator.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18sequence_generator.proto\"!\n\x0fSequenceRequest\x12\x0e\n\x06length\x18\x01 \x01(\x05\"$\n\x10SequenceResponse\x12\x10\n\x08sequence\x18\x01 \x03(\x01\x32L\n\x11SequenceGenerator\x12\x37\n\x10GenerateSequence\x12\x10.SequenceRequest\x1a\x11.SequenceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sequence_generator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEQUENCEREQUEST']._serialized_start=28
  _globals['_SEQUENCEREQUEST']._serialized_end=61
  _globals['_SEQUENCERESPONSE']._serialized_start=63
  _globals['_SEQUENCERESPONSE']._serialized_end=99
  _globals['_SEQUENCEGENERATOR']._serialized_start=101
  _globals['_SEQUENCEGENERATOR']._serialized_end=177
# @@protoc_insertion_point(module_scope)
